### PR TITLE
WIP: Add support for external textures

### PR DESCRIPTION
**Pull request by knopp**

### CODE REVIEW

**Comment by knopp** [comment]
Currently blocked on: 
- https://github.com/flutter/engine/pull/24916
- https://github.com/flutter/engine/pull/27522

**Comment by xtyxtyx** [comment]
Hello,

Is it possible to call `texture.update(PixelBuffer{...});` in other spawned threads?

I'm writing a video player and need to spawn a thread decoding the video, then supply decoded raw frames to the texture like this:
```rust
thread::spawn(move || {
    loop {
        // decoding stuff
        texture.update(...);
    }
});
```
When compiling I got:
```rust
`std::rc::Weak<ContextImpl>` cannot be sent between threads safely
within `[closure@src/main.rs:53:31: 55:18]`, the trait `Send` is not implemented for `std::rc::Weak<ContextImpl>`
required because it appears within the type `nativeshell::shell::Context`
required because it appears within the type `Texture<PixelBuffer>`
required because it appears within the type `[closure@src/main.rs:53:31: 55:18]`
```

Wrapping the texture with `Capsule` doesn't work either:
```rust
let texture = Capsule::new(texture);
thread::spawn(move || {
    loop {
        // decoding
        runloop_sender.send(|| {
            texture.get_ref().unwrap().update(...);
        });
    }
});
```
```rust
`std::rc::Weak<ContextImpl>` cannot be shared between threads safely
within `Capsule<Texture<PixelBuffer>>`, the trait `Sync` is not implemented for `std::rc::Weak<ContextImpl>`
required because it appears within the type `nativeshell::shell::Context`
required because it appears within the type `Texture<PixelBuffer>`
required because it appears within the type `Option<Texture<PixelBuffer>>`
required because it appears within the type `Capsule<Texture<PixelBuffer>>`
required because of the requirements on the impl of `Send` for `&Capsule<Texture<PixelBuffer>>`
required because it appears within the type `[closure@src/main.rs:66:38: 68:26]`
```

**Comment by knopp** [comment]
So, the problem is here (missing move):
```rust
let texture = Capsule::new(texture);
thread::spawn(move || {
    loop {
        // decoding
        runloop_sender.send(|| { // <--- you're missing move here
            texture.get_ref().unwrap().update(...);
        });
    }
});
```

You need to move the capsule between threads, because it is `Send` (can be moved between threads) but not `Sync` (can not be used from multiple threads at the same time). But, now issue is that you're calling `runloop_sender.send` in loop, so it will move out of texture in first iteration and after that there's nothing more to move.

So to get this working, you can wrap the capsule inside `Arc<Mutex<>>`

```rust
let texture = Capsule::new(texture);
let texture = Arc::new(Mutex::new(texture));
thread::spawn(move || {
    loop {
        // decoding
        let texture = texture.clone(); // clone texture here as it will be moved below
        runloop_sender.send(move || {
             let texture = texture.lock().unwrap(); // access the capsule
             texture.get_ref().unwrap().update(...);
        });
    }
});
```

**Comment by xtyxtyx** [comment]
> So to get this working, you can wrap the capsule inside Arc<Mutex<>>

This approach works, thank you so much!

**Comment by maxjoehnk** [comment]
As far as I can tell the upstream changes required for this are merged right?
Are you going to merge this pr or has your work shifted to the other repositories?

**Comment by knopp** [comment]
My work did have shift to other repositories. It seems like having something like this in NativeShell is just too limiting. Similar to drag & drop for example. With NativeShell you're constrained to desktop platforms, but [super_drag_and_drop](https://github.com/superlistapp/super_native_extensions/tree/main/super_drag_and_drop) works on all platforms.

So instead of having this in NativeShell, I'm experimenting with a crate that should work on all platforms, including iOS and Android. 

As a start, here is Flutter plugin and a crate that makes it possible to access TextureRegistry from FFi code:

https://github.com/nativeshell/ironbird/tree/main/engine_context/dart
https://github.com/nativeshell/ironbird/tree/main/engine_context/rust

**Comment by knopp** [comment]
Work on texture support is being continued here:

https://github.com/irondash/irondash/pull/8

**Pull request closed without merging**
